export const ALL_FOODS_REQUEST =  'ALL_FOODS_REQUEST';
export const ALL_FOODS_SUCCESS =  'ALL_FOODS_SUCCESS';
export const ALL_FOODS_FAIL =  'ALL_FOODS_FAIL';

export const CLEAR_ERRORS =  'CLEAR_ERRORS';